# Generated by Django 4.2.2 on 2024-04-04 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_doc', models.CharField(max_length=250)),
                ('dep', models.TextField(max_length=250)),
                ('image', models.ImageField(upload_to='images')),
            ],
        ),
    ]
